<!DOCTYPE html>
<html><head>

<script src="../lib/jquery-2.1.4.min.js"></script>
	<script src="../lib/jquery-ui.min.js"></script>	
	<link href="../lib/jquery-ui.css" rel="stylesheet"/>	
</head>
</html>

<h3 class="top"> . </h3>
<div class="menu">
	<div>		 
		<a href="/protect/power.html">Стрелки</a>
		<a href="/but/index.html">Кнопки1</a>
		<a href="/but/index2.html">Кнопки2</a>	
		<a href="/but/index3.html">Кнопки3</a>
		<a href="/but/index4.html">Кнопки4</a>
		<a href="/protect/sheduler.html">Планировщик</a>
		<a href="/protect/nest.html">Термостат</a>
		<a href="/protect/pchv.html">ПЧВ</a>
	</div>
	<div>		
		<a href="/protect/ps_online.html">Power online</a>	
		<a href="/protect/online.html">График online</a>	
		<a href="/protect/grafarhivlocal.html">График из файла</a>
		<a href="/protect/vishumpr.html">Виджет влажность/давление</a>
		<a href="/protect/visds.html">Виджет температура</a>	
		<a href="/protect/modbus.html">Управление запросами</a>
		<a href="/protect/demo512.html">Демо ПР200_ПРМ1</a>		 
		<a href="/heap.htm">HEAP монитор</a>
		<a href="/protect/smi.html">7 segment</a>	
		<a href="/protect/smi2.html">7 segment</a>	
	</div>
</div>
<script type="text/javascript">
config=~sys_config~;




</script>